### ISSUE TITLE
Add (tm) to the wordmark branding

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/branding#1]
As per @gmkurtzer's request

**Comment by morsik** [comment]
™ is for registered trademarks. There's no point of this issue until this will be actually registered trademark in US and EU.

**Comment by Addvilz** [comment]
It's the opposite - (TM) is for common law (unregistered) trade marks, (R) is for registered trade marks.

**Comment by morsik** [comment]
Oh! Sorry for mistake! I don't know where I got this from…
