### ISSUE TITLE
License text is BSD-3 but README states CC-BY-SA 4.0

### ISSUE THREAD

**Issue by ekohl** [rocky-linux/branding#3]
The [LICENSE](https://github.com/rocky-linux/branding/blob/main/LICENSE) file contains the BSD-3 text but [README.md](https://github.com/rocky-linux/branding/blob/main/README.md) states CC-BY-SA 4.0. I'm not a lawyer, but this looks odd to me. Could you explain to me what the situation is?

**Comment by thepappas** [comment]
We have same issue.  I work on behalf of a large corp that requires clarity of licensing.

**Comment by nazunalika** [comment]
Closing the issue as resolved.

**Comment by ekohl** [comment]
For those looking for the answer "what changed"? https://github.com/rocky-linux/branding/commit/5034ffcb4795c2f27f614990aed808ec53486143 changed the LICENSE file.
